# AUTOGENERATED! DO NOT EDIT! File to edit: ../057_robot-name.ipynb.

# %% auto 0
__all__ = ['Robot']

# %% ../057_robot-name.ipynb 4
import random
import string
import datetime

# %% ../057_robot-name.ipynb 5
class Robot:
    NAMES = []
    def __init__(self):
        random.seed(datetime.datetime.now())
        name = random.choice(string.ascii_uppercase)+random.choice(string.ascii_uppercase)+f"{random.randint(0,999):03d}"
        while name in Robot.NAMES:
            name = random.choice(string.ascii_uppercase)+random.choice(string.ascii_uppercase)+f"{random.randint(0,999):03d}"
        Robot.NAMES.append(name)
        self.name = name

    def reset(self):
        random.seed(datetime.datetime.now())
        name = random.choice(string.ascii_uppercase)+random.choice(string.ascii_uppercase)+f"{random.randint(0,999):03d}"
        while name in Robot.NAMES:
            name = random.choice(string.ascii_uppercase)+random.choice(string.ascii_uppercase)+f"{random.randint(0,999):03d}"
        Robot.NAMES.append(name)
        self.name = name
    def __repr__(self):
        return f"Robot name: {self.name}"
