# AUTOGENERATED! DO NOT EDIT! File to edit: ../057_robot-name.ipynb.

# %% auto 0
__all__ = ['Robot']

# %% ../057_robot-name.ipynb 5
from random import choice, randint, seed
from string import ascii_uppercase

# %% ../057_robot-name.ipynb 6
class Robot:
    "Generate robot with unique name"
    names: list[str] = []

    def __init__(self) -> None:
        self.name: str = Robot.validate_name()

    # Instructinos ask to create `reset` method, which in same as `__init__` method
    reset = __init__

    @staticmethod
    def generate_name() -> str:
        "Generate a unique robot name such as RX837 or BC811"
        seed()
        name: str = (
            choice(ascii_uppercase) + choice(ascii_uppercase) + f"{randint(0,999):03d}"
        )
        return name

    @staticmethod
    def validate_name() -> str:
        "Validate and return generated robot name"
        name: str = Robot.generate_name()
        while name in Robot.names:
            name = Robot.generate_name()
        Robot.names.append(name)
        return name
